controller_server:
  ros__parameters:
    controller_frequency: 30.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.001
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["goal_checker"]
    controller_plugins: ["FollowPath"]
    odom_topic: "/odom"
    publish_zero_velocity: true

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 1.0
      movement_time_allowance: 10.0
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 2.0
      yaw_goal_tolerance: 1.0
      stateful: True
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      transform_tolerance: 0.5

      allow_reversing: true

      desired_linear_vel: 0.5
      lookahead_dist: 1.0

      use_velocity_scaled_lookahead_dist: false  
      min_lookahead_dist: 2.0  
      max_lookahead_dist: 6.0 
      lookahead_time: 3.0 

      use_rotate_to_heading: false
      rotate_to_heading_angular_vel: 0.6 
      max_angular_accel: 0.15
      rotate_to_heading_min_angle: 0.0  

      min_approach_linear_velocity: 0.08
      approach_velocity_scaling_dist: 1.0  

      use_collision_detection: false  
      use_cost_regulated_linear_velocity_scaling: false 
      max_allowed_time_to_collision_up_to_carrot: 2.0  

      use_regulated_linear_velocity_scaling: true  
      regulated_linear_scaling_min_radius: 2.0
      regulated_linear_scaling_min_speed: 0.1 

      max_robot_pose_search_dist: 10.0

      use_interpolation: true
local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: True
      rolling_window: True
      width: 8
      height: 3
      resolution: 0.5
      footprint: "[ [-0.15, 0.3], [0.15,0.3], [0.15,0.225], [0.5,0.225], [0.5,-0.225], [0.15,-0.225], [0.15,-0.3], [-0.15,-0.3] ]"
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: pointcloud
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.3
      always_send_full_costmap: True
