ugv_nav4d_ros2:
  ros__parameters:
    spline_resolution_distance: 1.0
    read_pose_from_topic: false
    load_mls_from_file: true
    mls_file_type: "ply" #Options: bin, ply
    mls_file_path: '/fullpath/to/your_ros2_workspace/turtlebot3_nav2_ugv_nav4d_config/flat_plane_100x100_0pt1m.ply'
    mls_gap_size: 0.1
    robot_frame: base_link
    world_frame: odom
    grid_resolution: 0.2
    dist_max_x: 30
    dist_min_x: -30
    dist_max_y: 30
    dist_min_y: -30
    dist_max_z: 30
    dist_min_z: -30
    dumpOnError: false
    dumpOnSuccess: false
    initialPatchRadius: 5.0
    #Mobility Parameters
    maxMotionCurveLength: 100.0
    minTurningRadius: 1.0
    multiplierBackward: 1.0
    multiplierBackwardTurn: 3.0
    multiplierForward: 1.0
    multiplierForwardTurn: 3.0
    multiplierLateral: 4.0
    multiplierLateralCurve: 4.0
    multiplierPointTurn: 1.0
    rotationSpeed: 1.0
    searchProgressSteps: 0.1
    searchRadius: 1.0
    translationSpeed: 1.0   
    spline_sampling_resolution: 0.05
    remove_goal_offset: false
    #Planner Parameters
    epsilonSteps: 2
    initialEpsilon: 64
    numThreads: 8
    planningTime: 14000000
    #Motion Primitive Parameters:
    cellSkipFactor: 0.1
    destinationCircleRadius: 6
    generateBackwardMotions: true
    generateForwardMotions: true
    generateLateralMotions: false
    generatePointTurnMotions: false
    numAngles: 16
    numEndAngles: 8
    splineOrder: 4
    #Traversability Parameters:
    allowForwardDownhill: true
    costFunctionDist: 0.0
    distToGround: 0.0
    enableInclineLimitting: false
    inclineLimittingLimit: 0.1
    inclineLimittingMinSlope: 0.2
    initialPatchVariance: 0.0001
    maxSlope: 0.55
    maxStepHeight: 0.2
    minTraversablePercentage: 0.4
    robotHeight: 0.2
    robotSizeX: 0.3
    robotSizeY: 0.3
    slopeMetric: :NONE
    slopeMetricScale: 1.0
    #Trajectory Extension
    #The trajectory is extended in cases of direction 
    #change (Forward->Backward, Backward->Forward) and at final goal position
    #The extension is useful when using a Pure Pursuit path follower
    extend_trajectory: true
    extension_distance: 2.0 # in meters
